name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Push to gitee
      run: |
        ls ~/.ssh
        echo "${{ secrets.GITEE_RSA_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 0600 /root/.ssh/id_ed25519
        git clone git@gitee.com:sillybot/binary.git
