name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Get gox
      run: go get github.com/mitchellh/gox

    - name: Build
      run: gox -osarch "linux/amd64 linux/arm64"
      
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          sillyGirl_linux_amd64
          sillyGirl_linux_arm64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
