name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build amd64
      run: GOOS=linux GOARCH=amd64 go build -o sillyGirl_linux_amd64
      
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: sillyGirl_linux_amd64
        asset_name: sillyGirl_linux_amd64
        tag: ${{ github.ref }}
      
    - name: Build arm64
      run: GOOS=linux GOARCH=arm64 go build -o sillyGirl_linux_arm64
      
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: sillyGirl_linux_arm64
        asset_name: sillyGirl_linux_arm64
        tag: ${{ github.ref }}
      

