name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build amd64
      run: GOOS=linux GOARCH=amd64 go build main.go -o sillyGirl_linux_amd64
      
    - name: Build arm64
      run: GOOS=linux GOARCH=arm64 go build main.go -o sillyGirl_linux_arm64
      
    - name: Create GitHub release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ env.ReleaseVersion }}
        title: ${{ env.ReleaseVersion }}
        prerelease: false
        files: |
          sillyGirl_linux_amd64
          sillyGirl_linux_arm64
