name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: repo-sync
      uses: guojuna/git-repo-sync@master
      with:
        source_repo_url: git@github.com:cdle/binary.git
        source_branch: master
        dest_repo_url: git@gitee.com:sillybot/sillyGirl.git
        dest_branch: master
        ssh_private_key: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
