name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    env:
      dst_key: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      dst_token: ${{ secrets.GITEE_TOKEN }}
      gitee_user: sillybot    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: sync github -> gitee
      uses: Yikun/hub-mirror-action@master
      if: env.dst_key && env.dst_token && env.gitee_user
      with:
        src: 'github/cdle/binary'
        dst: 'github/sillybot/binary'
        dst_key: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        static_list: ${{ github.event.repository.name }}
